- name: Get MooseFS Cli Package
  get_url:
    url: http://ppa.moosefs.com/moosefs-2/apt/ubuntu/trusty/pool/main/m/moosefs/moosefs-cli_2.0.91-1_amd64.deb
    dest: /tmp/moosefs-cli_2.0.91-1_amd64.deb
- name: Get MooseFS Client Package
  get_url:
    url: http://ppa.moosefs.com/moosefs-2/apt/ubuntu/trusty/pool/main/m/moosefs/moosefs-client_2.0.91-1_amd64.deb
    dest: /tmp/moosefs-client_2.0.91-1_amd64.deb
- name: Install MooseFS Cli Package
  command: dpkg -i /tmp/moosefs-cli_2.0.91-1_amd64.deb
- name: Install MooseFS Client Package
  command: dpkg -i /tmp/moosefs-client_2.0.91-1_amd64.deb
- name: Mount MooseFS
  mount:
    name: /mfs
    src: mfsmount
    fstype: fuse
    opts: "{{ mfs_opts }}"
    state: "{{ mfs_state }}"