- name: Add hosts entry for apiserver.cluster.local
  lineinfile:
    dest: /etc/hosts
    regexp: '\s+apiserver.cluster.local(\s|$)'
    line: '127.0.0.1   apiserver.cluster.local'
  register: hosts_apiserver_updated
- name: Add IPv4 hosts entries for nodes
  lineinfile:
    dest: /etc/hosts
    regexp: '\d+\.\d+.*\s+{{ item }}(\s|$)'
    line: '{{ hostvars[item]["ansible_default_ipv4"]["address"] }}  {{ item }}.{{ fqdn_node_domain }} {{ item }}'
  with_items: '{{ play_hosts }}'
  register: hosts_node_ipv4_updated
- name: Add IPv6 hosts entries for nodes
  lineinfile:
    dest: /etc/hosts
    regexp: '.+:.+\s+{{ item }}(\s|$)'
    line: '{{ hostvars[item]["ansible_default_ipv6"]["address"] }}  {{ item }}.{{ fqdn_node_domain }} {{ item }}'
  when: '"address" in hostvars[item]["ansible_default_ipv6"]'
  with_items: '{{ play_hosts }}'
  register: hosts_node_ipv6_updated
- name: Reload facts
  setup:
    gather_subset=network
  when: hosts_apiserver_updated.changed or hosts_node_ipv4_updated.changed or hosts_node_ipv6_updated.changed
