- name: Set node hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}
  when: ansible_fqdn != "{{ inventory_hostname }}.node.cluster.local"
  register: hostname_updated
- name: Reload facts
  setup:
    gather_subset=network
  when: hostname_updated.changed
