- name: Install LVM
  yum:
    name: lvm2

- name: lvm.conf - thin_pool_autoextend_threshold
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: '^\s*thin_pool_autoextend_threshold.*'
    line: "\tthin_pool_autoextend_threshold = 80"
  register: thin_pool_autoextend_threshold
- name: lvm.conf - thin_pool_autoextend_percent
  lineinfile:
    dest: /etc/lvm/lvm.conf
    regexp: '^\s*thin_pool_autoextend_percent.*'
    line: "\tthin_pool_autoextend_percent = 20"
  register: thin_pool_autoextend_percent
- name: Restart lvm2-monitor.service
  command: systemctl restart lvm2-monitor.service
  when: thin_pool_autoextend_threshold.changed or thin_pool_autoextend_percent.changed

- name: Checking if volume group exists
  command: 'vgdisplay vg'
  changed_when: False
  failed_when: False
  register: check_vg_exists
- name: Configuring LVM to use /dev/vdb
  command: "{{ item }}"
  with_items:
  - parted /dev/vdb mklabel gpt
  - parted /dev/vdb mkpart gentoo ext2 1 -- -1
  - parted /dev/vdb set 1 lvm on
  - pvcreate /dev/vdb1
  - vgcreate vg /dev/vdb1
  when: check_vg_exists.rc != 0

