- name: Install build tools
  apt:
    name: build-essential
- name: Get NVIDIA Driver
  get_url:
    url: http://us.download.nvidia.com/XFree86/Linux-x86_64/375.39/NVIDIA-Linux-x86_64-375.39.run
    dest: /tmp/NVIDIA-Linux-x86_64-375.39.run
- name: Install NVIDIA Driver
  command: chmod +x /tmp/NVIDIA-Linux-x86_64-375.39.run && /tmp/NVIDIA-Linux-x86_64-375.39.run -a --ui=none --no-x-check && rm /tmp/NVIDIA-Linux-x86_64-375.39.run
- name: Remove build tools
  command: apt-get remove -y --auto-remove --purge build-essential make gcc gcc-5 cpp cpp-5 binutils