- name: Check if have Nvidia modules already
  command: /sbin/modprobe nvidia
  register: nvidia
  ignore_errors: True
  tags: gpu
- name: Install build tools
  apt:
    name: build-essential
  when: nvidia|failed
  tags: gpu
- name: Get NVIDIA Driver
  get_url:
    url: "http://us.download.nvidia.com/XFree86/Linux-x86_64/{{ nvidia_version }}/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run"
    dest: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
  when: nvidia|failed
  tags: gpu
- name: Fix NVIDIA Installer Permission
  command: chmod +x /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
  when: nvidia|failed
  tags: gpu
- name: Create installtion directory
  file:
    state: directory
    path: /usr/local/nvidia
    owner: root
    group: root
    mode: 0755
  when: nvidia|failed
  tags: gpu
- name: Install NVIDIA Driver
  command: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run --utility-prefix=/usr/local/nvidia --opengl-prefix=/usr/local/nvidia -a --ui=none -q --no-x-check --no-install-compat32-libs
  when: nvidia|failed
  tags: gpu
- name: Remove NVIDIA Installer
  command: rm /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
  when: nvidia|failed
  tags: gpu
- name: Remove build tools
  command: apt-get remove -y --auto-remove --purge build-essential make gcc gcc-5 cpp cpp-5 binutils
  when: nvidia|failed
  tags: gpu
- name: Blacklist nouveau
  kernel_blacklist:
    name: nouveau
    state: present
  when: nvidia|failed
  tags: gpu
- name: Update Initramfs to comply with kernel module settings
  command: update-initramfs -u
  tags: gpu
  when: nvidia|failed
- name: Check nvidia lib path in system library path
  command: grep -Fxq "/usr/local/nvidia/lib" /etc/ld.so.conf
  register: nvidia_lib
  ignore_errors: True
  tags: gpu
- name: Fix nvidia lib path
  lineinfile:
    dest=/etc/ld.so.conf
    backup=yes
    line="/usr/local/nvidia/lib"
    owner=root
    regexp='/usr/local/nvidia/lib'
    state=present
    insertafter=EOF
    create=True
  when: nvidia_lib|failed
  tags: gpu
- name: Update libs
  command: ldconfig
  when: nvidia_lib|failed
  tags: gpu
- name: Fix nvidia bin path
  lineinfile:
    dest=/etc/profile.d/nvidia.sh
    backup=yes
    line="export PATH=$PATH:/usr/local/nvidia/bin"
    owner=root
    regexp='export PATH=$PATH:/usr/local/nvidia/bin'
    state=present
    insertafter=EOF
    create=True
  when: nvidia_lib|failed
  tags: gpu
- name: Run nvidia installtion test
  command: /usr/local/nvidia/bin/nvidia-persistenced && /usr/local/nvidia/bin/nvidia-smi
  when: nvidia|failed
  tags: gpu
- name: Create nvidia UVM device
  command: /usr/bin/nvidia-modprobe -c0 -u
  when: nvidia|failed
  tags: gpu
- name: Attach nvidia-gpu labels
  command: kubectl --kubeconfig kubeconfig label --overwrite node {{ inventory_hostname }} nvidia-gpu=true
  delegate_to: localhost
  when: nvidia|failed
  become: false
  tags: gpu