- name: Check if have Nvidia modules already
  command: /sbin/modprobe nvidia
  register: nvidia
  ignore_errors: True
  tags: gpu
- name: Install build tools
  apt:
    name: build-essential
  when: nvidia|failed
  tags: gpu
- name: Get NVIDIA Driver
  get_url:
    url: "http://us.download.nvidia.com/XFree86/Linux-x86_64/{{ nvidia_version }}/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run"
    dest: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
  when: nvidia|failed
  tags: gpu
- name: Fix NVIDIA Installer Permission
  command: chmod +x /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
  when: nvidia|failed
  tags: gpu
- name: Install NVIDIA Driver
  command: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run -a --ui=none --no-x-check
  when: nvidia|failed
  tags: gpu
- name: Remove NVIDIA Installer
  command: rm /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
  when: nvidia|failed
  tags: gpu
- name: Remove build tools
  command: apt-get remove -y --auto-remove --purge build-essential make gcc gcc-5 cpp cpp-5 binutils
  when: nvidia|failed
  tags: gpu
- name: Blacklist nouveau
  kernel_blacklist:
    name: nouveau
    state: present
  when: nvidia|failed
  tags: gpu
- name: Update Initramfs to comply with kernel module settings
  command: update-initramfs -u
  tags: gpu
  when: nvidia|failed
- name: Get Nvidia-Docker Volume plugin
  get_url:
    url: https://github.com/NVIDIA/nvidia-docker/releases/download/v{{ nvidia_docker_ver }}/nvidia-docker_{{ nvidia_docker_ver }}-1_amd64.deb
    dest: /tmp/nvidia-docker_{{ nvidia_docker_ver }}-1_amd64.deb
  when: nvidia|failed
  tags: gpu
- name: Install Nvidia-Docker Volume plugin
  command: dpkg -i /tmp/nvidia-docker_{{ nvidia_docker_ver }}-1_amd64.deb
  when: nvidia|failed
  tags: gpu
- name: Fix Nvidia-Docker path issue
  copy:
    src: nvidia-docker.service
    dest: /lib/systemd/system/nvidia-docker.service
    owner: root
    group: root
    mode: 0644
  when: nvidia|failed
  tags: gpu
- name: Reloading systemd
  command: systemctl daemon-reload
  when: nvidia|failed
  tags: gpu
- name: restart nvidia-docker
  service: name=nvidia-docker state=restarted enabled=yes
  when: nvidia|failed
  tags: gpu
- name: Run test nvidia-docker
  command: nvidia-docker run --rm nvidia/cuda nvidia-smi
  when: nvidia|failed
  tags: gpu