- name: Work aruond docker blocking IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/00-forwarding.conf
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
- name: Install ca-certificates
  apt:
    name: ca-certificates
- name: Install curl
  apt:
    name: curl
- name: Get Docker GPG key
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /tmp/docker.gpg
- name: Add Docker GPG key
  command: apt-key add /tmp/docker.gpg
- name: Add Docker Repo
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: Create docker config folder
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Config Docker service
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: docker_svc
- name: Insert Overlay kernel module
  modprobe:
    name: overlay
    state: present
- name: Update apt cache
  command: apt-get update
- name: Unpin Docker version
  command: apt-mark unhold docker-ce
- name: Install Docker
  apt:
    name: "{{ docker_ver }}"
    force: yes
- name: Pin Docker version
  command: apt-mark hold docker-ce
- name: Create Docker systemd folder
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Copy Dockerd systemd fie
  copy:
    src: 01tasksmax.conf
    dest: /etc/systemd/system/docker.service.d/01tasksmax.conf
    owner: root
    group: root
    mode: 0644
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
- name: restart docker
  service: name=docker state=restarted enabled=yes
  when: docker_svc.changed
