- name: Work aruond docker blocking IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/00-forwarding.conf
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
- name: Install ca-certificates
  apt:
    name: ca-certificates
- name: Install curl
  apt:
    name: curl
- name: Get Docker GPG key
  get_url:
    url: "https://yum.dockerproject.org/gpg"
    dest: /tmp/docker.gpg
- name: Add Docker GPG key
  command: apt-key add /tmp/docker.gpg
- name: Add Docker Repo
  command: add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-xenial main"
- name: Create docker config folder
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Config Docker service
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: docker_svc
- name: Insert Overlay kernel module
  modprobe:
    name: overlay
    state: present
- name: Install Docker
  apt:
    name: "{{ docker_ver }}"
    update_cache: yes
- name: Pin Docker
  command: apt-mark hold docker-engine
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
- name: restart docker
  service: name=docker state=restarted enabled=yes
  when: docker_svc.changed
