- name: Work aruond docker blocking IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/00-forwarding.conf
- name: Check if docker thin-pool exists
  command: 'lvdisplay vg/docker'
  changed_when: False
  failed_when: False
  register: check_thinpool_exists
- name: create docker-thinpool
  command: lvcreate --type thin-pool -n docker -l 35%VG vg
  when: check_thinpool_exists.rc != 0
- name: Set up Docker YUM repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
- name: Install Docker
  yum:
    name: "{{ docker_ver }}"
- name: Create docker config folder
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Config Docker service
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
