- name: Work aruond docker blocking IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/00-forwarding.conf
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
- name: Install ca-certificates
  apt:
    name: ca-certificates
- name: Install curl
  apt:
    name: curl
- name: Install software-properties-common
  apt:
    name: software-properties-common
- name: Install python-apt
  apt:
    name: python-apt
- name: Get Docker GPG Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
- name: Add Docker GPG Key
  command: sudo apt-key add /tmp/docker.gpg
- name: Set up Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
- name: Create docker config folder
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Config Docker service
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  register: docker_svc
- name: Insert Overlay kernel module
  modprobe:
    name: overlay
    state: present
- name: Install Docker
  apt:
    name: "{{ docker_ver }}"
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
- name: restart docker
  service: name=docker state=restarted enabled=yes
  when: docker_svc.changed
