- name: Remove up ansible configuration of nodes
  hosts: servers
  tasks:
    - name: Get Nvidia Version
      include_vars:
        file: vars.yaml
    - name: Stop kubelet
      service:
        name: kubelet
        state: stopped
        enabled: no
      failed_when: False
    - name: Remove Docker containers
      command: sh -c "docker rm -f $(docker ps -aq)"
      ignore_errors: yes
    - name: Stop Docker
      service:
        name: docker
        state: stopped
        enabled: no
      failed_when: False
    - name: Remove Docker folder
      file:
        path: /var/lib/docker
        state: absent
      ignore_errors: yes
    - name: Remove kubelet service
      file:
        path: /etc/systemd/system/kubelet.service
        state: absent
    - name: Remove /etc/kubernetes configuration
      file:
        path: /etc/kubernetes
        state: absent
    - name: Remove /etc/cni configuration
      file:
        path: /etc/cni
        state: absent
    - name: Remove /opt/kubernetes
      file:
        path: /opt/kubernetes
        state: absent
    - name: Remove /opt/cni
      file:
        path: /opt/cni
        state: absent
    - name: Uninstall Docker
      apt:
        name: docker.io
        state: absent
    - name: Remove Docker configuration
      file:
        path: /etc/docker
        state: absent
    - name: Remove /etc/ssl/etcd
      file:
        path: /etc/ssl/etcd
        state: absent
    - name: Remove /var/lib/etcd
      file:
        path: /var/lib/etcd
        state: absent
    - name: Remove /var/backups/etcd
      file:
        path: /var/backups/etcd
        state: absent
    - name: Remove Kubelet mount points
      command: sh -c "mount |cut -d' ' -f 3|grep '/var/lib/kubelet/pods'| xargs -I {} umount {}"
    - name: Remove /var/lib/kubelet
      file:
        path: /var/lib/kubelet
        state: absent
      ignore_errors: yes
    - name: Stop zabbix
      service:
        name: zabbix-agent
        state: stopped
        enabled: no
      failed_when: False
    - name: Uninstall Zabbix
      apt:
        name: zabbix-agent
        state: absent
    - name: Clear iptables rules
      command: sh -c 'iptables -t nat -F; iptables -t nat -X; iptables -F; iptables -X'
    - name: Remove sysctl setting for net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        state: absent
        sysctl_file: /etc/sysctl.d/00-forwarding.conf
    - name: Make sure net.ipv4.ip_forward is set to 0
      command: sysctl net.ipv4.ip_forward=0
    - name: Check if have Nvidia modules already
      command: /sbin/modprobe nvidia
      register: nvidia
      ignore_errors: True
    - name: Get NVIDIA Driver
      get_url:
        url: "http://us.download.nvidia.com/XFree86/Linux-x86_64/{{ nvidia_version }}/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run"
        dest: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
      when: nvidia|succeeded
      tags: gpu
    - name: Fix NVIDIA Installer Permission
      command: chmod +x /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
      when: nvidia|succeeded
      tags: gpu
    - name: Remove NVIDIA Drivers
      command: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run -a --uninstall --ui=none --no-x-check
      when: nvidia|succeeded
    - name: Remove Nvidia Device service
      file:
        path: /etc/systemd/system/nvidia-device.service
        state: absent
      when: nvidia|succeeded
    - name: Remove NVIDIA Driver
      command: rm /tmp/NVIDIA-Linux-x86_64-{{ nvidia_version }}.run
      when: nvidia|succeeded