- name: Install python2
  hosts: servers
  gather_facts: False
  pre_tasks:
    - name: waiting for host to come online
      local_action: wait_for host={{ hostvars[inventory_hostname]['ansible_host'] }}
                state=started port=22
      become: false
    - name: Ensuring that sshd is running properly
      pause:
        seconds: 5
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
- name: Perform common node setup
  hosts: servers
  roles:
    - common