kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-list-authenticated
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-list-authenticated
subjects:
- kind: Group
  name: system:authenticated
roleRef:
  kind: ClusterRole
  name: namespace-list-authenticated
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: authenticated-discovery
subjects:
  - kind: Group
    name: system:authenticated
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: authenticated-default
  namespace: default
subjects:
  - kind: Group
    name: system:authenticated
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io